// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1ModuleTransactionReadParams creates a new V1ModuleTransactionReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1ModuleTransactionReadParams() *V1ModuleTransactionReadParams {
	return &V1ModuleTransactionReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1ModuleTransactionReadParamsWithTimeout creates a new V1ModuleTransactionReadParams object
// with the ability to set a timeout on a request.
func NewV1ModuleTransactionReadParamsWithTimeout(timeout time.Duration) *V1ModuleTransactionReadParams {
	return &V1ModuleTransactionReadParams{
		timeout: timeout,
	}
}

// NewV1ModuleTransactionReadParamsWithContext creates a new V1ModuleTransactionReadParams object
// with the ability to set a context for a request.
func NewV1ModuleTransactionReadParamsWithContext(ctx context.Context) *V1ModuleTransactionReadParams {
	return &V1ModuleTransactionReadParams{
		Context: ctx,
	}
}

// NewV1ModuleTransactionReadParamsWithHTTPClient creates a new V1ModuleTransactionReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1ModuleTransactionReadParamsWithHTTPClient(client *http.Client) *V1ModuleTransactionReadParams {
	return &V1ModuleTransactionReadParams{
		HTTPClient: client,
	}
}

/*
V1ModuleTransactionReadParams contains all the parameters to send to the API endpoint

	for the v1 module transaction read operation.

	Typically these are written to a http.Request.
*/
type V1ModuleTransactionReadParams struct {

	// ModuleTransactionID.
	ModuleTransactionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 module transaction read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1ModuleTransactionReadParams) WithDefaults() *V1ModuleTransactionReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 module transaction read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1ModuleTransactionReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) WithTimeout(timeout time.Duration) *V1ModuleTransactionReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) WithContext(ctx context.Context) *V1ModuleTransactionReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) WithHTTPClient(client *http.Client) *V1ModuleTransactionReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModuleTransactionID adds the moduleTransactionID to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) WithModuleTransactionID(moduleTransactionID string) *V1ModuleTransactionReadParams {
	o.SetModuleTransactionID(moduleTransactionID)
	return o
}

// SetModuleTransactionID adds the moduleTransactionId to the v1 module transaction read params
func (o *V1ModuleTransactionReadParams) SetModuleTransactionID(moduleTransactionID string) {
	o.ModuleTransactionID = moduleTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *V1ModuleTransactionReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param module_transaction_id
	if err := r.SetPathParam("module_transaction_id", o.ModuleTransactionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
