// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1SafesMultisigTransactionsEstimationsCreateReader is a Reader for the V1SafesMultisigTransactionsEstimationsCreate structure.
type V1SafesMultisigTransactionsEstimationsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1SafesMultisigTransactionsEstimationsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1SafesMultisigTransactionsEstimationsCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1SafesMultisigTransactionsEstimationsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1SafesMultisigTransactionsEstimationsCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/safes/{address}/multisig-transactions/estimations/] v1_safes_multisig-transactions_estimations_create", response, response.Code())
	}
}

// NewV1SafesMultisigTransactionsEstimationsCreateOK creates a V1SafesMultisigTransactionsEstimationsCreateOK with default headers values
func NewV1SafesMultisigTransactionsEstimationsCreateOK() *V1SafesMultisigTransactionsEstimationsCreateOK {
	return &V1SafesMultisigTransactionsEstimationsCreateOK{}
}

/*
V1SafesMultisigTransactionsEstimationsCreateOK describes a response with status code 200, with default header values.

V1SafesMultisigTransactionsEstimationsCreateOK v1 safes multisig transactions estimations create o k
*/
type V1SafesMultisigTransactionsEstimationsCreateOK struct {
	Payload *models.SafeMultisigTransactionEstimateResponse
}

// IsSuccess returns true when this v1 safes multisig transactions estimations create o k response has a 2xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 safes multisig transactions estimations create o k response has a 3xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes multisig transactions estimations create o k response has a 4xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 safes multisig transactions estimations create o k response has a 5xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes multisig transactions estimations create o k response a status code equal to that given
func (o *V1SafesMultisigTransactionsEstimationsCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 safes multisig transactions estimations create o k response
func (o *V1SafesMultisigTransactionsEstimationsCreateOK) Code() int {
	return 200
}

func (o *V1SafesMultisigTransactionsEstimationsCreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateOK %s", 200, payload)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateOK %s", 200, payload)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateOK) GetPayload() *models.SafeMultisigTransactionEstimateResponse {
	return o.Payload
}

func (o *V1SafesMultisigTransactionsEstimationsCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SafeMultisigTransactionEstimateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1SafesMultisigTransactionsEstimationsCreateBadRequest creates a V1SafesMultisigTransactionsEstimationsCreateBadRequest with default headers values
func NewV1SafesMultisigTransactionsEstimationsCreateBadRequest() *V1SafesMultisigTransactionsEstimationsCreateBadRequest {
	return &V1SafesMultisigTransactionsEstimationsCreateBadRequest{}
}

/*
V1SafesMultisigTransactionsEstimationsCreateBadRequest describes a response with status code 400, with default header values.

Data not valid
*/
type V1SafesMultisigTransactionsEstimationsCreateBadRequest struct {
}

// IsSuccess returns true when this v1 safes multisig transactions estimations create bad request response has a 2xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 safes multisig transactions estimations create bad request response has a 3xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes multisig transactions estimations create bad request response has a 4xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 safes multisig transactions estimations create bad request response has a 5xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes multisig transactions estimations create bad request response a status code equal to that given
func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the v1 safes multisig transactions estimations create bad request response
func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) Code() int {
	return 400
}

func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateBadRequest", 400)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateBadRequest", 400)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV1SafesMultisigTransactionsEstimationsCreateNotFound creates a V1SafesMultisigTransactionsEstimationsCreateNotFound with default headers values
func NewV1SafesMultisigTransactionsEstimationsCreateNotFound() *V1SafesMultisigTransactionsEstimationsCreateNotFound {
	return &V1SafesMultisigTransactionsEstimationsCreateNotFound{}
}

/*
V1SafesMultisigTransactionsEstimationsCreateNotFound describes a response with status code 404, with default header values.

Safe not found
*/
type V1SafesMultisigTransactionsEstimationsCreateNotFound struct {
}

// IsSuccess returns true when this v1 safes multisig transactions estimations create not found response has a 2xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 safes multisig transactions estimations create not found response has a 3xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes multisig transactions estimations create not found response has a 4xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 safes multisig transactions estimations create not found response has a 5xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes multisig transactions estimations create not found response a status code equal to that given
func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1 safes multisig transactions estimations create not found response
func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) Code() int {
	return 404
}

func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateNotFound", 404)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) String() string {
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateNotFound", 404)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity creates a V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity with default headers values
func NewV1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity() *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity {
	return &V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity{}
}

/*
V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity describes a response with status code 422, with default header values.

Tx not valid
*/
type V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity struct {
}

// IsSuccess returns true when this v1 safes multisig transactions estimations create unprocessable entity response has a 2xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 safes multisig transactions estimations create unprocessable entity response has a 3xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes multisig transactions estimations create unprocessable entity response has a 4xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 safes multisig transactions estimations create unprocessable entity response has a 5xx status code
func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes multisig transactions estimations create unprocessable entity response a status code equal to that given
func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v1 safes multisig transactions estimations create unprocessable entity response
func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) Code() int {
	return 422
}

func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity", 422)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /v1/safes/{address}/multisig-transactions/estimations/][%d] v1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity", 422)
}

func (o *V1SafesMultisigTransactionsEstimationsCreateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
