// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1TokensReadReader is a Reader for the V1TokensRead structure.
type V1TokensReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1TokensReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1TokensReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/tokens/{address}/] v1_tokens_read", response, response.Code())
	}
}

// NewV1TokensReadOK creates a V1TokensReadOK with default headers values
func NewV1TokensReadOK() *V1TokensReadOK {
	return &V1TokensReadOK{}
}

/*
V1TokensReadOK describes a response with status code 200, with default header values.

V1TokensReadOK v1 tokens read o k
*/
type V1TokensReadOK struct {
	Payload *models.TokenInfoResponse
}

// IsSuccess returns true when this v1 tokens read o k response has a 2xx status code
func (o *V1TokensReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 tokens read o k response has a 3xx status code
func (o *V1TokensReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 tokens read o k response has a 4xx status code
func (o *V1TokensReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 tokens read o k response has a 5xx status code
func (o *V1TokensReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 tokens read o k response a status code equal to that given
func (o *V1TokensReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 tokens read o k response
func (o *V1TokensReadOK) Code() int {
	return 200
}

func (o *V1TokensReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/tokens/{address}/][%d] v1TokensReadOK %s", 200, payload)
}

func (o *V1TokensReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/tokens/{address}/][%d] v1TokensReadOK %s", 200, payload)
}

func (o *V1TokensReadOK) GetPayload() *models.TokenInfoResponse {
	return o.Payload
}

func (o *V1TokensReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TokenInfoResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
