// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1ContractsReadParams creates a new V1ContractsReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1ContractsReadParams() *V1ContractsReadParams {
	return &V1ContractsReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1ContractsReadParamsWithTimeout creates a new V1ContractsReadParams object
// with the ability to set a timeout on a request.
func NewV1ContractsReadParamsWithTimeout(timeout time.Duration) *V1ContractsReadParams {
	return &V1ContractsReadParams{
		timeout: timeout,
	}
}

// NewV1ContractsReadParamsWithContext creates a new V1ContractsReadParams object
// with the ability to set a context for a request.
func NewV1ContractsReadParamsWithContext(ctx context.Context) *V1ContractsReadParams {
	return &V1ContractsReadParams{
		Context: ctx,
	}
}

// NewV1ContractsReadParamsWithHTTPClient creates a new V1ContractsReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1ContractsReadParamsWithHTTPClient(client *http.Client) *V1ContractsReadParams {
	return &V1ContractsReadParams{
		HTTPClient: client,
	}
}

/*
V1ContractsReadParams contains all the parameters to send to the API endpoint

	for the v1 contracts read operation.

	Typically these are written to a http.Request.
*/
type V1ContractsReadParams struct {

	/* Address.

	   A unique value identifying this contract.
	*/
	Address string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 contracts read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1ContractsReadParams) WithDefaults() *V1ContractsReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 contracts read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1ContractsReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 contracts read params
func (o *V1ContractsReadParams) WithTimeout(timeout time.Duration) *V1ContractsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 contracts read params
func (o *V1ContractsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 contracts read params
func (o *V1ContractsReadParams) WithContext(ctx context.Context) *V1ContractsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 contracts read params
func (o *V1ContractsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 contracts read params
func (o *V1ContractsReadParams) WithHTTPClient(client *http.Client) *V1ContractsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 contracts read params
func (o *V1ContractsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the v1 contracts read params
func (o *V1ContractsReadParams) WithAddress(address string) *V1ContractsReadParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the v1 contracts read params
func (o *V1ContractsReadParams) SetAddress(address string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *V1ContractsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
