// Code generated by go-swagger; DO NOT EDIT.

package safe_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SafeDeploymentContract safe deployment contract
//
// swagger:model SafeDeploymentContract
type SafeDeploymentContract struct {

	// Address
	// Required: true
	Address *string `json:"address"`

	// Contract name
	// Required: true
	// Min Length: 1
	ContractName *string `json:"contractName"`
}

// Validate validates this safe deployment contract
func (m *SafeDeploymentContract) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContractName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SafeDeploymentContract) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *SafeDeploymentContract) validateContractName(formats strfmt.Registry) error {

	if err := validate.Required("contractName", "body", m.ContractName); err != nil {
		return err
	}

	if err := validate.MinLength("contractName", "body", *m.ContractName, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this safe deployment contract based on context it is used
func (m *SafeDeploymentContract) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SafeDeploymentContract) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SafeDeploymentContract) UnmarshalBinary(b []byte) error {
	var res SafeDeploymentContract
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
