// Code generated by go-swagger; DO NOT EDIT.

package safe_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SafeMultisigTransactionDelete safe multisig transaction delete
//
// swagger:model SafeMultisigTransactionDelete
type SafeMultisigTransactionDelete struct {

	// Safe tx hash
	// Required: true
	SafeTxHash *string `json:"safeTxHash"`

	// Signature
	// Required: true
	Signature *string `json:"signature"`
}

// Validate validates this safe multisig transaction delete
func (m *SafeMultisigTransactionDelete) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSafeTxHash(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SafeMultisigTransactionDelete) validateSafeTxHash(formats strfmt.Registry) error {

	if err := validate.Required("safeTxHash", "body", m.SafeTxHash); err != nil {
		return err
	}

	return nil
}

func (m *SafeMultisigTransactionDelete) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this safe multisig transaction delete based on context it is used
func (m *SafeMultisigTransactionDelete) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SafeMultisigTransactionDelete) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SafeMultisigTransactionDelete) UnmarshalBinary(b []byte) error {
	var res SafeMultisigTransactionDelete
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
