// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// NewV1NotificationsDevicesCreateParams creates a new V1NotificationsDevicesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1NotificationsDevicesCreateParams() *V1NotificationsDevicesCreateParams {
	return &V1NotificationsDevicesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1NotificationsDevicesCreateParamsWithTimeout creates a new V1NotificationsDevicesCreateParams object
// with the ability to set a timeout on a request.
func NewV1NotificationsDevicesCreateParamsWithTimeout(timeout time.Duration) *V1NotificationsDevicesCreateParams {
	return &V1NotificationsDevicesCreateParams{
		timeout: timeout,
	}
}

// NewV1NotificationsDevicesCreateParamsWithContext creates a new V1NotificationsDevicesCreateParams object
// with the ability to set a context for a request.
func NewV1NotificationsDevicesCreateParamsWithContext(ctx context.Context) *V1NotificationsDevicesCreateParams {
	return &V1NotificationsDevicesCreateParams{
		Context: ctx,
	}
}

// NewV1NotificationsDevicesCreateParamsWithHTTPClient creates a new V1NotificationsDevicesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1NotificationsDevicesCreateParamsWithHTTPClient(client *http.Client) *V1NotificationsDevicesCreateParams {
	return &V1NotificationsDevicesCreateParams{
		HTTPClient: client,
	}
}

/*
V1NotificationsDevicesCreateParams contains all the parameters to send to the API endpoint

	for the v1 notifications devices create operation.

	Typically these are written to a http.Request.
*/
type V1NotificationsDevicesCreateParams struct {

	// Data.
	Data *models.FirebaseDevice

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 notifications devices create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1NotificationsDevicesCreateParams) WithDefaults() *V1NotificationsDevicesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 notifications devices create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1NotificationsDevicesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) WithTimeout(timeout time.Duration) *V1NotificationsDevicesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) WithContext(ctx context.Context) *V1NotificationsDevicesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) WithHTTPClient(client *http.Client) *V1NotificationsDevicesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) WithData(data *models.FirebaseDevice) *V1NotificationsDevicesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the v1 notifications devices create params
func (o *V1NotificationsDevicesCreateParams) SetData(data *models.FirebaseDevice) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *V1NotificationsDevicesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
