// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1NotificationsDevicesDeleteParams creates a new V1NotificationsDevicesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1NotificationsDevicesDeleteParams() *V1NotificationsDevicesDeleteParams {
	return &V1NotificationsDevicesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1NotificationsDevicesDeleteParamsWithTimeout creates a new V1NotificationsDevicesDeleteParams object
// with the ability to set a timeout on a request.
func NewV1NotificationsDevicesDeleteParamsWithTimeout(timeout time.Duration) *V1NotificationsDevicesDeleteParams {
	return &V1NotificationsDevicesDeleteParams{
		timeout: timeout,
	}
}

// NewV1NotificationsDevicesDeleteParamsWithContext creates a new V1NotificationsDevicesDeleteParams object
// with the ability to set a context for a request.
func NewV1NotificationsDevicesDeleteParamsWithContext(ctx context.Context) *V1NotificationsDevicesDeleteParams {
	return &V1NotificationsDevicesDeleteParams{
		Context: ctx,
	}
}

// NewV1NotificationsDevicesDeleteParamsWithHTTPClient creates a new V1NotificationsDevicesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1NotificationsDevicesDeleteParamsWithHTTPClient(client *http.Client) *V1NotificationsDevicesDeleteParams {
	return &V1NotificationsDevicesDeleteParams{
		HTTPClient: client,
	}
}

/*
V1NotificationsDevicesDeleteParams contains all the parameters to send to the API endpoint

	for the v1 notifications devices delete operation.

	Typically these are written to a http.Request.
*/
type V1NotificationsDevicesDeleteParams struct {

	/* UUID.

	   A UUID string identifying this Firebase Device.

	   Format: uuid
	*/
	UUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 notifications devices delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1NotificationsDevicesDeleteParams) WithDefaults() *V1NotificationsDevicesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 notifications devices delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1NotificationsDevicesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) WithTimeout(timeout time.Duration) *V1NotificationsDevicesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) WithContext(ctx context.Context) *V1NotificationsDevicesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) WithHTTPClient(client *http.Client) *V1NotificationsDevicesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) WithUUID(uuid strfmt.UUID) *V1NotificationsDevicesDeleteParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the v1 notifications devices delete params
func (o *V1NotificationsDevicesDeleteParams) SetUUID(uuid strfmt.UUID) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *V1NotificationsDevicesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
