// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1NotificationsDevicesDeleteReader is a Reader for the V1NotificationsDevicesDelete structure.
type V1NotificationsDevicesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1NotificationsDevicesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1NotificationsDevicesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/notifications/devices/{uuid}/] v1_notifications_devices_delete", response, response.Code())
	}
}

// NewV1NotificationsDevicesDeleteNoContent creates a V1NotificationsDevicesDeleteNoContent with default headers values
func NewV1NotificationsDevicesDeleteNoContent() *V1NotificationsDevicesDeleteNoContent {
	return &V1NotificationsDevicesDeleteNoContent{}
}

/*
V1NotificationsDevicesDeleteNoContent describes a response with status code 204, with default header values.

V1NotificationsDevicesDeleteNoContent v1 notifications devices delete no content
*/
type V1NotificationsDevicesDeleteNoContent struct {
}

// IsSuccess returns true when this v1 notifications devices delete no content response has a 2xx status code
func (o *V1NotificationsDevicesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 notifications devices delete no content response has a 3xx status code
func (o *V1NotificationsDevicesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 notifications devices delete no content response has a 4xx status code
func (o *V1NotificationsDevicesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 notifications devices delete no content response has a 5xx status code
func (o *V1NotificationsDevicesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 notifications devices delete no content response a status code equal to that given
func (o *V1NotificationsDevicesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the v1 notifications devices delete no content response
func (o *V1NotificationsDevicesDeleteNoContent) Code() int {
	return 204
}

func (o *V1NotificationsDevicesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/notifications/devices/{uuid}/][%d] v1NotificationsDevicesDeleteNoContent", 204)
}

func (o *V1NotificationsDevicesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /v1/notifications/devices/{uuid}/][%d] v1NotificationsDevicesDeleteNoContent", 204)
}

func (o *V1NotificationsDevicesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
