// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1NotificationsDevicesSafesDeleteParams creates a new V1NotificationsDevicesSafesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1NotificationsDevicesSafesDeleteParams() *V1NotificationsDevicesSafesDeleteParams {
	return &V1NotificationsDevicesSafesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1NotificationsDevicesSafesDeleteParamsWithTimeout creates a new V1NotificationsDevicesSafesDeleteParams object
// with the ability to set a timeout on a request.
func NewV1NotificationsDevicesSafesDeleteParamsWithTimeout(timeout time.Duration) *V1NotificationsDevicesSafesDeleteParams {
	return &V1NotificationsDevicesSafesDeleteParams{
		timeout: timeout,
	}
}

// NewV1NotificationsDevicesSafesDeleteParamsWithContext creates a new V1NotificationsDevicesSafesDeleteParams object
// with the ability to set a context for a request.
func NewV1NotificationsDevicesSafesDeleteParamsWithContext(ctx context.Context) *V1NotificationsDevicesSafesDeleteParams {
	return &V1NotificationsDevicesSafesDeleteParams{
		Context: ctx,
	}
}

// NewV1NotificationsDevicesSafesDeleteParamsWithHTTPClient creates a new V1NotificationsDevicesSafesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1NotificationsDevicesSafesDeleteParamsWithHTTPClient(client *http.Client) *V1NotificationsDevicesSafesDeleteParams {
	return &V1NotificationsDevicesSafesDeleteParams{
		HTTPClient: client,
	}
}

/*
V1NotificationsDevicesSafesDeleteParams contains all the parameters to send to the API endpoint

	for the v1 notifications devices safes delete operation.

	Typically these are written to a http.Request.
*/
type V1NotificationsDevicesSafesDeleteParams struct {

	// Address.
	Address string

	/* UUID.

	   A UUID string identifying this Firebase Device.

	   Format: uuid
	*/
	UUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 notifications devices safes delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1NotificationsDevicesSafesDeleteParams) WithDefaults() *V1NotificationsDevicesSafesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 notifications devices safes delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1NotificationsDevicesSafesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) WithTimeout(timeout time.Duration) *V1NotificationsDevicesSafesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) WithContext(ctx context.Context) *V1NotificationsDevicesSafesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) WithHTTPClient(client *http.Client) *V1NotificationsDevicesSafesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) WithAddress(address string) *V1NotificationsDevicesSafesDeleteParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) SetAddress(address string) {
	o.Address = address
}

// WithUUID adds the uuid to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) WithUUID(uuid strfmt.UUID) *V1NotificationsDevicesSafesDeleteParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the v1 notifications devices safes delete params
func (o *V1NotificationsDevicesSafesDeleteParams) SetUUID(uuid strfmt.UUID) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *V1NotificationsDevicesSafesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
