// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1NotificationsDevicesSafesDeleteReader is a Reader for the V1NotificationsDevicesSafesDelete structure.
type V1NotificationsDevicesSafesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1NotificationsDevicesSafesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1NotificationsDevicesSafesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/notifications/devices/{uuid}/safes/{address}/] v1_notifications_devices_safes_delete", response, response.Code())
	}
}

// NewV1NotificationsDevicesSafesDeleteNoContent creates a V1NotificationsDevicesSafesDeleteNoContent with default headers values
func NewV1NotificationsDevicesSafesDeleteNoContent() *V1NotificationsDevicesSafesDeleteNoContent {
	return &V1NotificationsDevicesSafesDeleteNoContent{}
}

/*
V1NotificationsDevicesSafesDeleteNoContent describes a response with status code 204, with default header values.

V1NotificationsDevicesSafesDeleteNoContent v1 notifications devices safes delete no content
*/
type V1NotificationsDevicesSafesDeleteNoContent struct {
}

// IsSuccess returns true when this v1 notifications devices safes delete no content response has a 2xx status code
func (o *V1NotificationsDevicesSafesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 notifications devices safes delete no content response has a 3xx status code
func (o *V1NotificationsDevicesSafesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 notifications devices safes delete no content response has a 4xx status code
func (o *V1NotificationsDevicesSafesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 notifications devices safes delete no content response has a 5xx status code
func (o *V1NotificationsDevicesSafesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 notifications devices safes delete no content response a status code equal to that given
func (o *V1NotificationsDevicesSafesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the v1 notifications devices safes delete no content response
func (o *V1NotificationsDevicesSafesDeleteNoContent) Code() int {
	return 204
}

func (o *V1NotificationsDevicesSafesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/notifications/devices/{uuid}/safes/{address}/][%d] v1NotificationsDevicesSafesDeleteNoContent", 204)
}

func (o *V1NotificationsDevicesSafesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /v1/notifications/devices/{uuid}/safes/{address}/][%d] v1NotificationsDevicesSafesDeleteNoContent", 204)
}

func (o *V1NotificationsDevicesSafesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
