// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1SafesBalancesListReader is a Reader for the V1SafesBalancesList structure.
type V1SafesBalancesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1SafesBalancesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1SafesBalancesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewV1SafesBalancesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1SafesBalancesListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/safes/{address}/balances/] v1_safes_balances_list", response, response.Code())
	}
}

// NewV1SafesBalancesListOK creates a V1SafesBalancesListOK with default headers values
func NewV1SafesBalancesListOK() *V1SafesBalancesListOK {
	return &V1SafesBalancesListOK{}
}

/*
V1SafesBalancesListOK describes a response with status code 200, with default header values.

V1SafesBalancesListOK v1 safes balances list o k
*/
type V1SafesBalancesListOK struct {
	Payload []*models.SafeBalanceResponse
}

// IsSuccess returns true when this v1 safes balances list o k response has a 2xx status code
func (o *V1SafesBalancesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 safes balances list o k response has a 3xx status code
func (o *V1SafesBalancesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes balances list o k response has a 4xx status code
func (o *V1SafesBalancesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 safes balances list o k response has a 5xx status code
func (o *V1SafesBalancesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes balances list o k response a status code equal to that given
func (o *V1SafesBalancesListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 safes balances list o k response
func (o *V1SafesBalancesListOK) Code() int {
	return 200
}

func (o *V1SafesBalancesListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/safes/{address}/balances/][%d] v1SafesBalancesListOK %s", 200, payload)
}

func (o *V1SafesBalancesListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/safes/{address}/balances/][%d] v1SafesBalancesListOK %s", 200, payload)
}

func (o *V1SafesBalancesListOK) GetPayload() []*models.SafeBalanceResponse {
	return o.Payload
}

func (o *V1SafesBalancesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1SafesBalancesListNotFound creates a V1SafesBalancesListNotFound with default headers values
func NewV1SafesBalancesListNotFound() *V1SafesBalancesListNotFound {
	return &V1SafesBalancesListNotFound{}
}

/*
V1SafesBalancesListNotFound describes a response with status code 404, with default header values.

Safe not found
*/
type V1SafesBalancesListNotFound struct {
}

// IsSuccess returns true when this v1 safes balances list not found response has a 2xx status code
func (o *V1SafesBalancesListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 safes balances list not found response has a 3xx status code
func (o *V1SafesBalancesListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes balances list not found response has a 4xx status code
func (o *V1SafesBalancesListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 safes balances list not found response has a 5xx status code
func (o *V1SafesBalancesListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes balances list not found response a status code equal to that given
func (o *V1SafesBalancesListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1 safes balances list not found response
func (o *V1SafesBalancesListNotFound) Code() int {
	return 404
}

func (o *V1SafesBalancesListNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/safes/{address}/balances/][%d] v1SafesBalancesListNotFound", 404)
}

func (o *V1SafesBalancesListNotFound) String() string {
	return fmt.Sprintf("[GET /v1/safes/{address}/balances/][%d] v1SafesBalancesListNotFound", 404)
}

func (o *V1SafesBalancesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV1SafesBalancesListUnprocessableEntity creates a V1SafesBalancesListUnprocessableEntity with default headers values
func NewV1SafesBalancesListUnprocessableEntity() *V1SafesBalancesListUnprocessableEntity {
	return &V1SafesBalancesListUnprocessableEntity{}
}

/*
V1SafesBalancesListUnprocessableEntity describes a response with status code 422, with default header values.

Safe address checksum not valid
*/
type V1SafesBalancesListUnprocessableEntity struct {
}

// IsSuccess returns true when this v1 safes balances list unprocessable entity response has a 2xx status code
func (o *V1SafesBalancesListUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 safes balances list unprocessable entity response has a 3xx status code
func (o *V1SafesBalancesListUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes balances list unprocessable entity response has a 4xx status code
func (o *V1SafesBalancesListUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 safes balances list unprocessable entity response has a 5xx status code
func (o *V1SafesBalancesListUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes balances list unprocessable entity response a status code equal to that given
func (o *V1SafesBalancesListUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v1 safes balances list unprocessable entity response
func (o *V1SafesBalancesListUnprocessableEntity) Code() int {
	return 422
}

func (o *V1SafesBalancesListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /v1/safes/{address}/balances/][%d] v1SafesBalancesListUnprocessableEntity", 422)
}

func (o *V1SafesBalancesListUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /v1/safes/{address}/balances/][%d] v1SafesBalancesListUnprocessableEntity", 422)
}

func (o *V1SafesBalancesListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
