// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1SafesReadParams creates a new V1SafesReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1SafesReadParams() *V1SafesReadParams {
	return &V1SafesReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1SafesReadParamsWithTimeout creates a new V1SafesReadParams object
// with the ability to set a timeout on a request.
func NewV1SafesReadParamsWithTimeout(timeout time.Duration) *V1SafesReadParams {
	return &V1SafesReadParams{
		timeout: timeout,
	}
}

// NewV1SafesReadParamsWithContext creates a new V1SafesReadParams object
// with the ability to set a context for a request.
func NewV1SafesReadParamsWithContext(ctx context.Context) *V1SafesReadParams {
	return &V1SafesReadParams{
		Context: ctx,
	}
}

// NewV1SafesReadParamsWithHTTPClient creates a new V1SafesReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1SafesReadParamsWithHTTPClient(client *http.Client) *V1SafesReadParams {
	return &V1SafesReadParams{
		HTTPClient: client,
	}
}

/*
V1SafesReadParams contains all the parameters to send to the API endpoint

	for the v1 safes read operation.

	Typically these are written to a http.Request.
*/
type V1SafesReadParams struct {

	// Address.
	Address string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 safes read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1SafesReadParams) WithDefaults() *V1SafesReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 safes read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1SafesReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 safes read params
func (o *V1SafesReadParams) WithTimeout(timeout time.Duration) *V1SafesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 safes read params
func (o *V1SafesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 safes read params
func (o *V1SafesReadParams) WithContext(ctx context.Context) *V1SafesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 safes read params
func (o *V1SafesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 safes read params
func (o *V1SafesReadParams) WithHTTPClient(client *http.Client) *V1SafesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 safes read params
func (o *V1SafesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the v1 safes read params
func (o *V1SafesReadParams) WithAddress(address string) *V1SafesReadParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the v1 safes read params
func (o *V1SafesReadParams) SetAddress(address string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *V1SafesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
