// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V2SafesCollectiblesListReader is a Reader for the V2SafesCollectiblesList structure.
type V2SafesCollectiblesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2SafesCollectiblesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2SafesCollectiblesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewV2SafesCollectiblesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV2SafesCollectiblesListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v2/safes/{address}/collectibles/] v2_safes_collectibles_list", response, response.Code())
	}
}

// NewV2SafesCollectiblesListOK creates a V2SafesCollectiblesListOK with default headers values
func NewV2SafesCollectiblesListOK() *V2SafesCollectiblesListOK {
	return &V2SafesCollectiblesListOK{}
}

/*
V2SafesCollectiblesListOK describes a response with status code 200, with default header values.

V2SafesCollectiblesListOK v2 safes collectibles list o k
*/
type V2SafesCollectiblesListOK struct {
	Payload []*models.SafeCollectibleResponse
}

// IsSuccess returns true when this v2 safes collectibles list o k response has a 2xx status code
func (o *V2SafesCollectiblesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v2 safes collectibles list o k response has a 3xx status code
func (o *V2SafesCollectiblesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 safes collectibles list o k response has a 4xx status code
func (o *V2SafesCollectiblesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v2 safes collectibles list o k response has a 5xx status code
func (o *V2SafesCollectiblesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 safes collectibles list o k response a status code equal to that given
func (o *V2SafesCollectiblesListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v2 safes collectibles list o k response
func (o *V2SafesCollectiblesListOK) Code() int {
	return 200
}

func (o *V2SafesCollectiblesListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v2/safes/{address}/collectibles/][%d] v2SafesCollectiblesListOK %s", 200, payload)
}

func (o *V2SafesCollectiblesListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v2/safes/{address}/collectibles/][%d] v2SafesCollectiblesListOK %s", 200, payload)
}

func (o *V2SafesCollectiblesListOK) GetPayload() []*models.SafeCollectibleResponse {
	return o.Payload
}

func (o *V2SafesCollectiblesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2SafesCollectiblesListNotFound creates a V2SafesCollectiblesListNotFound with default headers values
func NewV2SafesCollectiblesListNotFound() *V2SafesCollectiblesListNotFound {
	return &V2SafesCollectiblesListNotFound{}
}

/*
V2SafesCollectiblesListNotFound describes a response with status code 404, with default header values.

Safe not found
*/
type V2SafesCollectiblesListNotFound struct {
}

// IsSuccess returns true when this v2 safes collectibles list not found response has a 2xx status code
func (o *V2SafesCollectiblesListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 safes collectibles list not found response has a 3xx status code
func (o *V2SafesCollectiblesListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 safes collectibles list not found response has a 4xx status code
func (o *V2SafesCollectiblesListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 safes collectibles list not found response has a 5xx status code
func (o *V2SafesCollectiblesListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 safes collectibles list not found response a status code equal to that given
func (o *V2SafesCollectiblesListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v2 safes collectibles list not found response
func (o *V2SafesCollectiblesListNotFound) Code() int {
	return 404
}

func (o *V2SafesCollectiblesListNotFound) Error() string {
	return fmt.Sprintf("[GET /v2/safes/{address}/collectibles/][%d] v2SafesCollectiblesListNotFound", 404)
}

func (o *V2SafesCollectiblesListNotFound) String() string {
	return fmt.Sprintf("[GET /v2/safes/{address}/collectibles/][%d] v2SafesCollectiblesListNotFound", 404)
}

func (o *V2SafesCollectiblesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV2SafesCollectiblesListUnprocessableEntity creates a V2SafesCollectiblesListUnprocessableEntity with default headers values
func NewV2SafesCollectiblesListUnprocessableEntity() *V2SafesCollectiblesListUnprocessableEntity {
	return &V2SafesCollectiblesListUnprocessableEntity{}
}

/*
V2SafesCollectiblesListUnprocessableEntity describes a response with status code 422, with default header values.

Safe address checksum not valid
*/
type V2SafesCollectiblesListUnprocessableEntity struct {
}

// IsSuccess returns true when this v2 safes collectibles list unprocessable entity response has a 2xx status code
func (o *V2SafesCollectiblesListUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 safes collectibles list unprocessable entity response has a 3xx status code
func (o *V2SafesCollectiblesListUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 safes collectibles list unprocessable entity response has a 4xx status code
func (o *V2SafesCollectiblesListUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 safes collectibles list unprocessable entity response has a 5xx status code
func (o *V2SafesCollectiblesListUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 safes collectibles list unprocessable entity response a status code equal to that given
func (o *V2SafesCollectiblesListUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v2 safes collectibles list unprocessable entity response
func (o *V2SafesCollectiblesListUnprocessableEntity) Code() int {
	return 422
}

func (o *V2SafesCollectiblesListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /v2/safes/{address}/collectibles/][%d] v2SafesCollectiblesListUnprocessableEntity", 422)
}

func (o *V2SafesCollectiblesListUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /v2/safes/{address}/collectibles/][%d] v2SafesCollectiblesListUnprocessableEntity", 422)
}

func (o *V2SafesCollectiblesListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
