// Code generated by go-swagger; DO NOT EDIT.

package owners

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1OwnersSafesListReader is a Reader for the V1OwnersSafesList structure.
type V1OwnersSafesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1OwnersSafesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1OwnersSafesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewV1OwnersSafesListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/owners/{address}/safes/] v1_owners_safes_list", response, response.Code())
	}
}

// NewV1OwnersSafesListOK creates a V1OwnersSafesListOK with default headers values
func NewV1OwnersSafesListOK() *V1OwnersSafesListOK {
	return &V1OwnersSafesListOK{}
}

/*
V1OwnersSafesListOK describes a response with status code 200, with default header values.

V1OwnersSafesListOK v1 owners safes list o k
*/
type V1OwnersSafesListOK struct {
	Payload *models.OwnerResponse
}

// IsSuccess returns true when this v1 owners safes list o k response has a 2xx status code
func (o *V1OwnersSafesListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 owners safes list o k response has a 3xx status code
func (o *V1OwnersSafesListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 owners safes list o k response has a 4xx status code
func (o *V1OwnersSafesListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 owners safes list o k response has a 5xx status code
func (o *V1OwnersSafesListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 owners safes list o k response a status code equal to that given
func (o *V1OwnersSafesListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 owners safes list o k response
func (o *V1OwnersSafesListOK) Code() int {
	return 200
}

func (o *V1OwnersSafesListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/owners/{address}/safes/][%d] v1OwnersSafesListOK %s", 200, payload)
}

func (o *V1OwnersSafesListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/owners/{address}/safes/][%d] v1OwnersSafesListOK %s", 200, payload)
}

func (o *V1OwnersSafesListOK) GetPayload() *models.OwnerResponse {
	return o.Payload
}

func (o *V1OwnersSafesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OwnerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1OwnersSafesListUnprocessableEntity creates a V1OwnersSafesListUnprocessableEntity with default headers values
func NewV1OwnersSafesListUnprocessableEntity() *V1OwnersSafesListUnprocessableEntity {
	return &V1OwnersSafesListUnprocessableEntity{}
}

/*
V1OwnersSafesListUnprocessableEntity describes a response with status code 422, with default header values.

Owner address checksum not valid
*/
type V1OwnersSafesListUnprocessableEntity struct {
}

// IsSuccess returns true when this v1 owners safes list unprocessable entity response has a 2xx status code
func (o *V1OwnersSafesListUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 owners safes list unprocessable entity response has a 3xx status code
func (o *V1OwnersSafesListUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 owners safes list unprocessable entity response has a 4xx status code
func (o *V1OwnersSafesListUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 owners safes list unprocessable entity response has a 5xx status code
func (o *V1OwnersSafesListUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 owners safes list unprocessable entity response a status code equal to that given
func (o *V1OwnersSafesListUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v1 owners safes list unprocessable entity response
func (o *V1OwnersSafesListUnprocessableEntity) Code() int {
	return 422
}

func (o *V1OwnersSafesListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /v1/owners/{address}/safes/][%d] v1OwnersSafesListUnprocessableEntity", 422)
}

func (o *V1OwnersSafesListUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /v1/owners/{address}/safes/][%d] v1OwnersSafesListUnprocessableEntity", 422)
}

func (o *V1OwnersSafesListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
