// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1TransferReadReader is a Reader for the V1TransferRead structure.
type V1TransferReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1TransferReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1TransferReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1TransferReadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1TransferReadNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/transfer/{transfer_id}] v1_transfer_read", response, response.Code())
	}
}

// NewV1TransferReadOK creates a V1TransferReadOK with default headers values
func NewV1TransferReadOK() *V1TransferReadOK {
	return &V1TransferReadOK{}
}

/*
V1TransferReadOK describes a response with status code 200, with default header values.

V1TransferReadOK v1 transfer read o k
*/
type V1TransferReadOK struct {
	Payload *models.TransferWithTokenInfoResponse
}

// IsSuccess returns true when this v1 transfer read o k response has a 2xx status code
func (o *V1TransferReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 transfer read o k response has a 3xx status code
func (o *V1TransferReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 transfer read o k response has a 4xx status code
func (o *V1TransferReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 transfer read o k response has a 5xx status code
func (o *V1TransferReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 transfer read o k response a status code equal to that given
func (o *V1TransferReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 transfer read o k response
func (o *V1TransferReadOK) Code() int {
	return 200
}

func (o *V1TransferReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/transfer/{transfer_id}][%d] v1TransferReadOK %s", 200, payload)
}

func (o *V1TransferReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/transfer/{transfer_id}][%d] v1TransferReadOK %s", 200, payload)
}

func (o *V1TransferReadOK) GetPayload() *models.TransferWithTokenInfoResponse {
	return o.Payload
}

func (o *V1TransferReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TransferWithTokenInfoResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1TransferReadBadRequest creates a V1TransferReadBadRequest with default headers values
func NewV1TransferReadBadRequest() *V1TransferReadBadRequest {
	return &V1TransferReadBadRequest{}
}

/*
V1TransferReadBadRequest describes a response with status code 400, with default header values.

Invalid transferId
*/
type V1TransferReadBadRequest struct {
}

// IsSuccess returns true when this v1 transfer read bad request response has a 2xx status code
func (o *V1TransferReadBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 transfer read bad request response has a 3xx status code
func (o *V1TransferReadBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 transfer read bad request response has a 4xx status code
func (o *V1TransferReadBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 transfer read bad request response has a 5xx status code
func (o *V1TransferReadBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 transfer read bad request response a status code equal to that given
func (o *V1TransferReadBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the v1 transfer read bad request response
func (o *V1TransferReadBadRequest) Code() int {
	return 400
}

func (o *V1TransferReadBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/transfer/{transfer_id}][%d] v1TransferReadBadRequest", 400)
}

func (o *V1TransferReadBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/transfer/{transfer_id}][%d] v1TransferReadBadRequest", 400)
}

func (o *V1TransferReadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV1TransferReadNotFound creates a V1TransferReadNotFound with default headers values
func NewV1TransferReadNotFound() *V1TransferReadNotFound {
	return &V1TransferReadNotFound{}
}

/*
V1TransferReadNotFound describes a response with status code 404, with default header values.

Transfer does not exist
*/
type V1TransferReadNotFound struct {
}

// IsSuccess returns true when this v1 transfer read not found response has a 2xx status code
func (o *V1TransferReadNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 transfer read not found response has a 3xx status code
func (o *V1TransferReadNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 transfer read not found response has a 4xx status code
func (o *V1TransferReadNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 transfer read not found response has a 5xx status code
func (o *V1TransferReadNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 transfer read not found response a status code equal to that given
func (o *V1TransferReadNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1 transfer read not found response
func (o *V1TransferReadNotFound) Code() int {
	return 404
}

func (o *V1TransferReadNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/transfer/{transfer_id}][%d] v1TransferReadNotFound", 404)
}

func (o *V1TransferReadNotFound) String() string {
	return fmt.Sprintf("[GET /v1/transfer/{transfer_id}][%d] v1TransferReadNotFound", 404)
}

func (o *V1TransferReadNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
