// Code generated by go-swagger; DO NOT EDIT.

package nr4337

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new nr4337 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new nr4337 API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new nr4337 API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for nr4337 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	V1SafeOperationsRead(params *V1SafeOperationsReadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafeOperationsReadOK, error)

	V1SafesSafeOperationsCreate(params *V1SafesSafeOperationsCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafesSafeOperationsCreateCreated, error)

	V1SafesSafeOperationsList(params *V1SafesSafeOperationsListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafesSafeOperationsListOK, error)

	V1SafesUserOperationsList(params *V1SafesUserOperationsListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafesUserOperationsListOK, error)

	V1UserOperationsRead(params *V1UserOperationsReadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1UserOperationsReadOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
V1SafeOperationsRead v1 safe operations read API
*/
func (a *Client) V1SafeOperationsRead(params *V1SafeOperationsReadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafeOperationsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1SafeOperationsReadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "v1_safe-operations_read",
		Method:             "GET",
		PathPattern:        "/v1/safe-operations/{safe_operation_hash}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &V1SafeOperationsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1SafeOperationsReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for v1_safe-operations_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	V1SafesSafeOperationsCreate creates a new 4337 safe operation for a safe

	:param request:

:param address:
:param args:
:param kwargs:
:return:
*/
func (a *Client) V1SafesSafeOperationsCreate(params *V1SafesSafeOperationsCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafesSafeOperationsCreateCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1SafesSafeOperationsCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "v1_safes_safe-operations_create",
		Method:             "POST",
		PathPattern:        "/v1/safes/{address}/safe-operations/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &V1SafesSafeOperationsCreateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1SafesSafeOperationsCreateCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for v1_safes_safe-operations_create: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
V1SafesSafeOperationsList v1 safes safe operations list API
*/
func (a *Client) V1SafesSafeOperationsList(params *V1SafesSafeOperationsListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafesSafeOperationsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1SafesSafeOperationsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "v1_safes_safe-operations_list",
		Method:             "GET",
		PathPattern:        "/v1/safes/{address}/safe-operations/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &V1SafesSafeOperationsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1SafesSafeOperationsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for v1_safes_safe-operations_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
V1SafesUserOperationsList v1 safes user operations list API
*/
func (a *Client) V1SafesUserOperationsList(params *V1SafesUserOperationsListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1SafesUserOperationsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1SafesUserOperationsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "v1_safes_user-operations_list",
		Method:             "GET",
		PathPattern:        "/v1/safes/{address}/user-operations/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &V1SafesUserOperationsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1SafesUserOperationsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for v1_safes_user-operations_list: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
V1UserOperationsRead v1 user operations read API
*/
func (a *Client) V1UserOperationsRead(params *V1UserOperationsReadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*V1UserOperationsReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1UserOperationsReadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "v1_user-operations_read",
		Method:             "GET",
		PathPattern:        "/v1/user-operations/{user_operation_hash}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &V1UserOperationsReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1UserOperationsReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for v1_user-operations_read: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
