// Code generated by go-swagger; DO NOT EDIT.

package nr4337

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	models "omni-balance/utils/safe_api"
)

// V1SafesSafeOperationsListReader is a Reader for the V1SafesSafeOperationsList structure.
type V1SafesSafeOperationsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1SafesSafeOperationsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1SafesSafeOperationsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/safes/{address}/safe-operations/] v1_safes_safe-operations_list", response, response.Code())
	}
}

// NewV1SafesSafeOperationsListOK creates a V1SafesSafeOperationsListOK with default headers values
func NewV1SafesSafeOperationsListOK() *V1SafesSafeOperationsListOK {
	return &V1SafesSafeOperationsListOK{}
}

/*
V1SafesSafeOperationsListOK describes a response with status code 200, with default header values.

V1SafesSafeOperationsListOK v1 safes safe operations list o k
*/
type V1SafesSafeOperationsListOK struct {
	Payload *V1SafesSafeOperationsListOKBody
}

// IsSuccess returns true when this v1 safes safe operations list o k response has a 2xx status code
func (o *V1SafesSafeOperationsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 safes safe operations list o k response has a 3xx status code
func (o *V1SafesSafeOperationsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 safes safe operations list o k response has a 4xx status code
func (o *V1SafesSafeOperationsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 safes safe operations list o k response has a 5xx status code
func (o *V1SafesSafeOperationsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 safes safe operations list o k response a status code equal to that given
func (o *V1SafesSafeOperationsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 safes safe operations list o k response
func (o *V1SafesSafeOperationsListOK) Code() int {
	return 200
}

func (o *V1SafesSafeOperationsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/safes/{address}/safe-operations/][%d] v1SafesSafeOperationsListOK %s", 200, payload)
}

func (o *V1SafesSafeOperationsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/safes/{address}/safe-operations/][%d] v1SafesSafeOperationsListOK %s", 200, payload)
}

func (o *V1SafesSafeOperationsListOK) GetPayload() *V1SafesSafeOperationsListOKBody {
	return o.Payload
}

func (o *V1SafesSafeOperationsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(V1SafesSafeOperationsListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
V1SafesSafeOperationsListOKBody v1 safes safe operations list o k body
swagger:model V1SafesSafeOperationsListOKBody
*/
type V1SafesSafeOperationsListOKBody struct {

	// count
	// Required: true
	Count *int64 `json:"count"`

	// next
	// Format: uri
	Next *strfmt.URI `json:"next,omitempty"`

	// previous
	// Format: uri
	Previous *strfmt.URI `json:"previous,omitempty"`

	// results
	// Required: true
	Results []*models.SafeOperationWithUserOperationResponse `json:"results"`
}

// Validate validates this v1 safes safe operations list o k body
func (o *V1SafesSafeOperationsListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *V1SafesSafeOperationsListOKBody) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("v1SafesSafeOperationsListOK"+"."+"count", "body", o.Count); err != nil {
		return err
	}

	return nil
}

func (o *V1SafesSafeOperationsListOKBody) validateNext(formats strfmt.Registry) error {
	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if err := validate.FormatOf("v1SafesSafeOperationsListOK"+"."+"next", "body", "uri", o.Next.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *V1SafesSafeOperationsListOKBody) validatePrevious(formats strfmt.Registry) error {
	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if err := validate.FormatOf("v1SafesSafeOperationsListOK"+"."+"previous", "body", "uri", o.Previous.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *V1SafesSafeOperationsListOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("v1SafesSafeOperationsListOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("v1SafesSafeOperationsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("v1SafesSafeOperationsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 safes safe operations list o k body based on the context it is used
func (o *V1SafesSafeOperationsListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *V1SafesSafeOperationsListOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {

			if swag.IsZero(o.Results[i]) { // not required
				return nil
			}

			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("v1SafesSafeOperationsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("v1SafesSafeOperationsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *V1SafesSafeOperationsListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *V1SafesSafeOperationsListOKBody) UnmarshalBinary(b []byte) error {
	var res V1SafesSafeOperationsListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
