// Code generated by go-swagger; DO NOT EDIT.

package nr4337

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewV1SafesUserOperationsListParams creates a new V1SafesUserOperationsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1SafesUserOperationsListParams() *V1SafesUserOperationsListParams {
	return &V1SafesUserOperationsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1SafesUserOperationsListParamsWithTimeout creates a new V1SafesUserOperationsListParams object
// with the ability to set a timeout on a request.
func NewV1SafesUserOperationsListParamsWithTimeout(timeout time.Duration) *V1SafesUserOperationsListParams {
	return &V1SafesUserOperationsListParams{
		timeout: timeout,
	}
}

// NewV1SafesUserOperationsListParamsWithContext creates a new V1SafesUserOperationsListParams object
// with the ability to set a context for a request.
func NewV1SafesUserOperationsListParamsWithContext(ctx context.Context) *V1SafesUserOperationsListParams {
	return &V1SafesUserOperationsListParams{
		Context: ctx,
	}
}

// NewV1SafesUserOperationsListParamsWithHTTPClient creates a new V1SafesUserOperationsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1SafesUserOperationsListParamsWithHTTPClient(client *http.Client) *V1SafesUserOperationsListParams {
	return &V1SafesUserOperationsListParams{
		HTTPClient: client,
	}
}

/*
V1SafesUserOperationsListParams contains all the parameters to send to the API endpoint

	for the v1 safes user operations list operation.

	Typically these are written to a http.Request.
*/
type V1SafesUserOperationsListParams struct {

	// Address.
	Address string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	/* Ordering.

	   Which field to use when ordering the results.
	*/
	Ordering *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 safes user operations list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1SafesUserOperationsListParams) WithDefaults() *V1SafesUserOperationsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 safes user operations list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1SafesUserOperationsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) WithTimeout(timeout time.Duration) *V1SafesUserOperationsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) WithContext(ctx context.Context) *V1SafesUserOperationsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) WithHTTPClient(client *http.Client) *V1SafesUserOperationsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) WithAddress(address string) *V1SafesUserOperationsListParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) SetAddress(address string) {
	o.Address = address
}

// WithLimit adds the limit to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) WithLimit(limit *int64) *V1SafesUserOperationsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) WithOffset(offset *int64) *V1SafesUserOperationsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) WithOrdering(ordering *string) *V1SafesUserOperationsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the v1 safes user operations list params
func (o *V1SafesUserOperationsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WriteToRequest writes these params to a swagger request
func (o *V1SafesUserOperationsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string

		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {

			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
