// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1ModulesSafesListParams creates a new V1ModulesSafesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1ModulesSafesListParams() *V1ModulesSafesListParams {
	return &V1ModulesSafesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1ModulesSafesListParamsWithTimeout creates a new V1ModulesSafesListParams object
// with the ability to set a timeout on a request.
func NewV1ModulesSafesListParamsWithTimeout(timeout time.Duration) *V1ModulesSafesListParams {
	return &V1ModulesSafesListParams{
		timeout: timeout,
	}
}

// NewV1ModulesSafesListParamsWithContext creates a new V1ModulesSafesListParams object
// with the ability to set a context for a request.
func NewV1ModulesSafesListParamsWithContext(ctx context.Context) *V1ModulesSafesListParams {
	return &V1ModulesSafesListParams{
		Context: ctx,
	}
}

// NewV1ModulesSafesListParamsWithHTTPClient creates a new V1ModulesSafesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1ModulesSafesListParamsWithHTTPClient(client *http.Client) *V1ModulesSafesListParams {
	return &V1ModulesSafesListParams{
		HTTPClient: client,
	}
}

/*
V1ModulesSafesListParams contains all the parameters to send to the API endpoint

	for the v1 modules safes list operation.

	Typically these are written to a http.Request.
*/
type V1ModulesSafesListParams struct {

	// Address.
	Address string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 modules safes list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1ModulesSafesListParams) WithDefaults() *V1ModulesSafesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 modules safes list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1ModulesSafesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 modules safes list params
func (o *V1ModulesSafesListParams) WithTimeout(timeout time.Duration) *V1ModulesSafesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 modules safes list params
func (o *V1ModulesSafesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 modules safes list params
func (o *V1ModulesSafesListParams) WithContext(ctx context.Context) *V1ModulesSafesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 modules safes list params
func (o *V1ModulesSafesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 modules safes list params
func (o *V1ModulesSafesListParams) WithHTTPClient(client *http.Client) *V1ModulesSafesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 modules safes list params
func (o *V1ModulesSafesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the v1 modules safes list params
func (o *V1ModulesSafesListParams) WithAddress(address string) *V1ModulesSafesListParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the v1 modules safes list params
func (o *V1ModulesSafesListParams) SetAddress(address string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *V1ModulesSafesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
