// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1AboutIndexingListReader is a Reader for the V1AboutIndexingList structure.
type V1AboutIndexingListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AboutIndexingListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AboutIndexingListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/about/indexing/] v1_about_indexing_list", response, response.Code())
	}
}

// NewV1AboutIndexingListOK creates a V1AboutIndexingListOK with default headers values
func NewV1AboutIndexingListOK() *V1AboutIndexingListOK {
	return &V1AboutIndexingListOK{}
}

/*
V1AboutIndexingListOK describes a response with status code 200, with default header values.

V1AboutIndexingListOK v1 about indexing list o k
*/
type V1AboutIndexingListOK struct {
	Payload []*models.IndexingStatus
}

// IsSuccess returns true when this v1 about indexing list o k response has a 2xx status code
func (o *V1AboutIndexingListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 about indexing list o k response has a 3xx status code
func (o *V1AboutIndexingListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 about indexing list o k response has a 4xx status code
func (o *V1AboutIndexingListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 about indexing list o k response has a 5xx status code
func (o *V1AboutIndexingListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 about indexing list o k response a status code equal to that given
func (o *V1AboutIndexingListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 about indexing list o k response
func (o *V1AboutIndexingListOK) Code() int {
	return 200
}

func (o *V1AboutIndexingListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/about/indexing/][%d] v1AboutIndexingListOK %s", 200, payload)
}

func (o *V1AboutIndexingListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/about/indexing/][%d] v1AboutIndexingListOK %s", 200, payload)
}

func (o *V1AboutIndexingListOK) GetPayload() []*models.IndexingStatus {
	return o.Payload
}

func (o *V1AboutIndexingListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
