// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1AboutIndexingListParams creates a new V1AboutIndexingListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1AboutIndexingListParams() *V1AboutIndexingListParams {
	return &V1AboutIndexingListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1AboutIndexingListParamsWithTimeout creates a new V1AboutIndexingListParams object
// with the ability to set a timeout on a request.
func NewV1AboutIndexingListParamsWithTimeout(timeout time.Duration) *V1AboutIndexingListParams {
	return &V1AboutIndexingListParams{
		timeout: timeout,
	}
}

// NewV1AboutIndexingListParamsWithContext creates a new V1AboutIndexingListParams object
// with the ability to set a context for a request.
func NewV1AboutIndexingListParamsWithContext(ctx context.Context) *V1AboutIndexingListParams {
	return &V1AboutIndexingListParams{
		Context: ctx,
	}
}

// NewV1AboutIndexingListParamsWithHTTPClient creates a new V1AboutIndexingListParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1AboutIndexingListParamsWithHTTPClient(client *http.Client) *V1AboutIndexingListParams {
	return &V1AboutIndexingListParams{
		HTTPClient: client,
	}
}

/*
V1AboutIndexingListParams contains all the parameters to send to the API endpoint

	for the v1 about indexing list operation.

	Typically these are written to a http.Request.
*/
type V1AboutIndexingListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 about indexing list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutIndexingListParams) WithDefaults() *V1AboutIndexingListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 about indexing list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutIndexingListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 about indexing list params
func (o *V1AboutIndexingListParams) WithTimeout(timeout time.Duration) *V1AboutIndexingListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 about indexing list params
func (o *V1AboutIndexingListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 about indexing list params
func (o *V1AboutIndexingListParams) WithContext(ctx context.Context) *V1AboutIndexingListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 about indexing list params
func (o *V1AboutIndexingListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 about indexing list params
func (o *V1AboutIndexingListParams) WithHTTPClient(client *http.Client) *V1AboutIndexingListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 about indexing list params
func (o *V1AboutIndexingListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1AboutIndexingListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
