// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1AboutListReader is a Reader for the V1AboutList structure.
type V1AboutListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AboutListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AboutListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/about/] v1_about_list", response, response.Code())
	}
}

// NewV1AboutListOK creates a V1AboutListOK with default headers values
func NewV1AboutListOK() *V1AboutListOK {
	return &V1AboutListOK{}
}

/*
V1AboutListOK describes a response with status code 200, with default header values.

V1AboutListOK v1 about list o k
*/
type V1AboutListOK struct {
}

// IsSuccess returns true when this v1 about list o k response has a 2xx status code
func (o *V1AboutListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 about list o k response has a 3xx status code
func (o *V1AboutListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 about list o k response has a 4xx status code
func (o *V1AboutListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 about list o k response has a 5xx status code
func (o *V1AboutListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 about list o k response a status code equal to that given
func (o *V1AboutListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 about list o k response
func (o *V1AboutListOK) Code() int {
	return 200
}

func (o *V1AboutListOK) Error() string {
	return fmt.Sprintf("[GET /v1/about/][%d] v1AboutListOK", 200)
}

func (o *V1AboutListOK) String() string {
	return fmt.Sprintf("[GET /v1/about/][%d] v1AboutListOK", 200)
}

func (o *V1AboutListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
