// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1AboutEthereumTracingRPCListParams creates a new V1AboutEthereumTracingRPCListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1AboutEthereumTracingRPCListParams() *V1AboutEthereumTracingRPCListParams {
	return &V1AboutEthereumTracingRPCListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1AboutEthereumTracingRPCListParamsWithTimeout creates a new V1AboutEthereumTracingRPCListParams object
// with the ability to set a timeout on a request.
func NewV1AboutEthereumTracingRPCListParamsWithTimeout(timeout time.Duration) *V1AboutEthereumTracingRPCListParams {
	return &V1AboutEthereumTracingRPCListParams{
		timeout: timeout,
	}
}

// NewV1AboutEthereumTracingRPCListParamsWithContext creates a new V1AboutEthereumTracingRPCListParams object
// with the ability to set a context for a request.
func NewV1AboutEthereumTracingRPCListParamsWithContext(ctx context.Context) *V1AboutEthereumTracingRPCListParams {
	return &V1AboutEthereumTracingRPCListParams{
		Context: ctx,
	}
}

// NewV1AboutEthereumTracingRPCListParamsWithHTTPClient creates a new V1AboutEthereumTracingRPCListParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1AboutEthereumTracingRPCListParamsWithHTTPClient(client *http.Client) *V1AboutEthereumTracingRPCListParams {
	return &V1AboutEthereumTracingRPCListParams{
		HTTPClient: client,
	}
}

/*
V1AboutEthereumTracingRPCListParams contains all the parameters to send to the API endpoint

	for the v1 about ethereum tracing rpc list operation.

	Typically these are written to a http.Request.
*/
type V1AboutEthereumTracingRPCListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 about ethereum tracing rpc list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutEthereumTracingRPCListParams) WithDefaults() *V1AboutEthereumTracingRPCListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 about ethereum tracing rpc list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutEthereumTracingRPCListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 about ethereum tracing rpc list params
func (o *V1AboutEthereumTracingRPCListParams) WithTimeout(timeout time.Duration) *V1AboutEthereumTracingRPCListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 about ethereum tracing rpc list params
func (o *V1AboutEthereumTracingRPCListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 about ethereum tracing rpc list params
func (o *V1AboutEthereumTracingRPCListParams) WithContext(ctx context.Context) *V1AboutEthereumTracingRPCListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 about ethereum tracing rpc list params
func (o *V1AboutEthereumTracingRPCListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 about ethereum tracing rpc list params
func (o *V1AboutEthereumTracingRPCListParams) WithHTTPClient(client *http.Client) *V1AboutEthereumTracingRPCListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 about ethereum tracing rpc list params
func (o *V1AboutEthereumTracingRPCListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1AboutEthereumTracingRPCListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
