// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1AboutEthereumTracingRPCListReader is a Reader for the V1AboutEthereumTracingRPCList structure.
type V1AboutEthereumTracingRPCListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AboutEthereumTracingRPCListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AboutEthereumTracingRPCListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/about/ethereum-tracing-rpc/] v1_about_ethereum-tracing-rpc_list", response, response.Code())
	}
}

// NewV1AboutEthereumTracingRPCListOK creates a V1AboutEthereumTracingRPCListOK with default headers values
func NewV1AboutEthereumTracingRPCListOK() *V1AboutEthereumTracingRPCListOK {
	return &V1AboutEthereumTracingRPCListOK{}
}

/*
V1AboutEthereumTracingRPCListOK describes a response with status code 200, with default header values.

V1AboutEthereumTracingRPCListOK v1 about ethereum tracing Rpc list o k
*/
type V1AboutEthereumTracingRPCListOK struct {
}

// IsSuccess returns true when this v1 about ethereum tracing Rpc list o k response has a 2xx status code
func (o *V1AboutEthereumTracingRPCListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 about ethereum tracing Rpc list o k response has a 3xx status code
func (o *V1AboutEthereumTracingRPCListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 about ethereum tracing Rpc list o k response has a 4xx status code
func (o *V1AboutEthereumTracingRPCListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 about ethereum tracing Rpc list o k response has a 5xx status code
func (o *V1AboutEthereumTracingRPCListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 about ethereum tracing Rpc list o k response a status code equal to that given
func (o *V1AboutEthereumTracingRPCListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 about ethereum tracing Rpc list o k response
func (o *V1AboutEthereumTracingRPCListOK) Code() int {
	return 200
}

func (o *V1AboutEthereumTracingRPCListOK) Error() string {
	return fmt.Sprintf("[GET /v1/about/ethereum-tracing-rpc/][%d] v1AboutEthereumTracingRpcListOK", 200)
}

func (o *V1AboutEthereumTracingRPCListOK) String() string {
	return fmt.Sprintf("[GET /v1/about/ethereum-tracing-rpc/][%d] v1AboutEthereumTracingRpcListOK", 200)
}

func (o *V1AboutEthereumTracingRPCListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
