// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1AboutEthereumRPCListReader is a Reader for the V1AboutEthereumRPCList structure.
type V1AboutEthereumRPCListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AboutEthereumRPCListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AboutEthereumRPCListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/about/ethereum-rpc/] v1_about_ethereum-rpc_list", response, response.Code())
	}
}

// NewV1AboutEthereumRPCListOK creates a V1AboutEthereumRPCListOK with default headers values
func NewV1AboutEthereumRPCListOK() *V1AboutEthereumRPCListOK {
	return &V1AboutEthereumRPCListOK{}
}

/*
V1AboutEthereumRPCListOK describes a response with status code 200, with default header values.

V1AboutEthereumRPCListOK v1 about ethereum Rpc list o k
*/
type V1AboutEthereumRPCListOK struct {
}

// IsSuccess returns true when this v1 about ethereum Rpc list o k response has a 2xx status code
func (o *V1AboutEthereumRPCListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 about ethereum Rpc list o k response has a 3xx status code
func (o *V1AboutEthereumRPCListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 about ethereum Rpc list o k response has a 4xx status code
func (o *V1AboutEthereumRPCListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 about ethereum Rpc list o k response has a 5xx status code
func (o *V1AboutEthereumRPCListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 about ethereum Rpc list o k response a status code equal to that given
func (o *V1AboutEthereumRPCListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 about ethereum Rpc list o k response
func (o *V1AboutEthereumRPCListOK) Code() int {
	return 200
}

func (o *V1AboutEthereumRPCListOK) Error() string {
	return fmt.Sprintf("[GET /v1/about/ethereum-rpc/][%d] v1AboutEthereumRpcListOK", 200)
}

func (o *V1AboutEthereumRPCListOK) String() string {
	return fmt.Sprintf("[GET /v1/about/ethereum-rpc/][%d] v1AboutEthereumRpcListOK", 200)
}

func (o *V1AboutEthereumRPCListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
