// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1AboutSingletonsListReader is a Reader for the V1AboutSingletonsList structure.
type V1AboutSingletonsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AboutSingletonsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AboutSingletonsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/about/singletons/] v1_about_singletons_list", response, response.Code())
	}
}

// NewV1AboutSingletonsListOK creates a V1AboutSingletonsListOK with default headers values
func NewV1AboutSingletonsListOK() *V1AboutSingletonsListOK {
	return &V1AboutSingletonsListOK{}
}

/*
V1AboutSingletonsListOK describes a response with status code 200, with default header values.

V1AboutSingletonsListOK v1 about singletons list o k
*/
type V1AboutSingletonsListOK struct {
	Payload []*models.MasterCopyResponse
}

// IsSuccess returns true when this v1 about singletons list o k response has a 2xx status code
func (o *V1AboutSingletonsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 about singletons list o k response has a 3xx status code
func (o *V1AboutSingletonsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 about singletons list o k response has a 4xx status code
func (o *V1AboutSingletonsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 about singletons list o k response has a 5xx status code
func (o *V1AboutSingletonsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 about singletons list o k response a status code equal to that given
func (o *V1AboutSingletonsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 about singletons list o k response
func (o *V1AboutSingletonsListOK) Code() int {
	return 200
}

func (o *V1AboutSingletonsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/about/singletons/][%d] v1AboutSingletonsListOK %s", 200, payload)
}

func (o *V1AboutSingletonsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/about/singletons/][%d] v1AboutSingletonsListOK %s", 200, payload)
}

func (o *V1AboutSingletonsListOK) GetPayload() []*models.MasterCopyResponse {
	return o.Payload
}

func (o *V1AboutSingletonsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
