// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1AboutEthereumRPCListParams creates a new V1AboutEthereumRPCListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1AboutEthereumRPCListParams() *V1AboutEthereumRPCListParams {
	return &V1AboutEthereumRPCListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1AboutEthereumRPCListParamsWithTimeout creates a new V1AboutEthereumRPCListParams object
// with the ability to set a timeout on a request.
func NewV1AboutEthereumRPCListParamsWithTimeout(timeout time.Duration) *V1AboutEthereumRPCListParams {
	return &V1AboutEthereumRPCListParams{
		timeout: timeout,
	}
}

// NewV1AboutEthereumRPCListParamsWithContext creates a new V1AboutEthereumRPCListParams object
// with the ability to set a context for a request.
func NewV1AboutEthereumRPCListParamsWithContext(ctx context.Context) *V1AboutEthereumRPCListParams {
	return &V1AboutEthereumRPCListParams{
		Context: ctx,
	}
}

// NewV1AboutEthereumRPCListParamsWithHTTPClient creates a new V1AboutEthereumRPCListParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1AboutEthereumRPCListParamsWithHTTPClient(client *http.Client) *V1AboutEthereumRPCListParams {
	return &V1AboutEthereumRPCListParams{
		HTTPClient: client,
	}
}

/*
V1AboutEthereumRPCListParams contains all the parameters to send to the API endpoint

	for the v1 about ethereum rpc list operation.

	Typically these are written to a http.Request.
*/
type V1AboutEthereumRPCListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 about ethereum rpc list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutEthereumRPCListParams) WithDefaults() *V1AboutEthereumRPCListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 about ethereum rpc list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutEthereumRPCListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 about ethereum rpc list params
func (o *V1AboutEthereumRPCListParams) WithTimeout(timeout time.Duration) *V1AboutEthereumRPCListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 about ethereum rpc list params
func (o *V1AboutEthereumRPCListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 about ethereum rpc list params
func (o *V1AboutEthereumRPCListParams) WithContext(ctx context.Context) *V1AboutEthereumRPCListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 about ethereum rpc list params
func (o *V1AboutEthereumRPCListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 about ethereum rpc list params
func (o *V1AboutEthereumRPCListParams) WithHTTPClient(client *http.Client) *V1AboutEthereumRPCListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 about ethereum rpc list params
func (o *V1AboutEthereumRPCListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1AboutEthereumRPCListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
