// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// V1AboutDeploymentsListReader is a Reader for the V1AboutDeploymentsList structure.
type V1AboutDeploymentsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AboutDeploymentsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AboutDeploymentsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewV1AboutDeploymentsListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/about/deployments/] v1_about_deployments_list", response, response.Code())
	}
}

// NewV1AboutDeploymentsListOK creates a V1AboutDeploymentsListOK with default headers values
func NewV1AboutDeploymentsListOK() *V1AboutDeploymentsListOK {
	return &V1AboutDeploymentsListOK{}
}

/*
V1AboutDeploymentsListOK describes a response with status code 200, with default header values.

V1AboutDeploymentsListOK v1 about deployments list o k
*/
type V1AboutDeploymentsListOK struct {
	Payload []*models.SafeDeployment
}

// IsSuccess returns true when this v1 about deployments list o k response has a 2xx status code
func (o *V1AboutDeploymentsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 about deployments list o k response has a 3xx status code
func (o *V1AboutDeploymentsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 about deployments list o k response has a 4xx status code
func (o *V1AboutDeploymentsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 about deployments list o k response has a 5xx status code
func (o *V1AboutDeploymentsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 about deployments list o k response a status code equal to that given
func (o *V1AboutDeploymentsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 about deployments list o k response
func (o *V1AboutDeploymentsListOK) Code() int {
	return 200
}

func (o *V1AboutDeploymentsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/about/deployments/][%d] v1AboutDeploymentsListOK %s", 200, payload)
}

func (o *V1AboutDeploymentsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/about/deployments/][%d] v1AboutDeploymentsListOK %s", 200, payload)
}

func (o *V1AboutDeploymentsListOK) GetPayload() []*models.SafeDeployment {
	return o.Payload
}

func (o *V1AboutDeploymentsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1AboutDeploymentsListNotFound creates a V1AboutDeploymentsListNotFound with default headers values
func NewV1AboutDeploymentsListNotFound() *V1AboutDeploymentsListNotFound {
	return &V1AboutDeploymentsListNotFound{}
}

/*
V1AboutDeploymentsListNotFound describes a response with status code 404, with default header values.

Provided version does not exist
*/
type V1AboutDeploymentsListNotFound struct {
}

// IsSuccess returns true when this v1 about deployments list not found response has a 2xx status code
func (o *V1AboutDeploymentsListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 about deployments list not found response has a 3xx status code
func (o *V1AboutDeploymentsListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 about deployments list not found response has a 4xx status code
func (o *V1AboutDeploymentsListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 about deployments list not found response has a 5xx status code
func (o *V1AboutDeploymentsListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 about deployments list not found response a status code equal to that given
func (o *V1AboutDeploymentsListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1 about deployments list not found response
func (o *V1AboutDeploymentsListNotFound) Code() int {
	return 404
}

func (o *V1AboutDeploymentsListNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/about/deployments/][%d] v1AboutDeploymentsListNotFound", 404)
}

func (o *V1AboutDeploymentsListNotFound) String() string {
	return fmt.Sprintf("[GET /v1/about/deployments/][%d] v1AboutDeploymentsListNotFound", 404)
}

func (o *V1AboutDeploymentsListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
