// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1AboutDeploymentsListParams creates a new V1AboutDeploymentsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1AboutDeploymentsListParams() *V1AboutDeploymentsListParams {
	return &V1AboutDeploymentsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1AboutDeploymentsListParamsWithTimeout creates a new V1AboutDeploymentsListParams object
// with the ability to set a timeout on a request.
func NewV1AboutDeploymentsListParamsWithTimeout(timeout time.Duration) *V1AboutDeploymentsListParams {
	return &V1AboutDeploymentsListParams{
		timeout: timeout,
	}
}

// NewV1AboutDeploymentsListParamsWithContext creates a new V1AboutDeploymentsListParams object
// with the ability to set a context for a request.
func NewV1AboutDeploymentsListParamsWithContext(ctx context.Context) *V1AboutDeploymentsListParams {
	return &V1AboutDeploymentsListParams{
		Context: ctx,
	}
}

// NewV1AboutDeploymentsListParamsWithHTTPClient creates a new V1AboutDeploymentsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1AboutDeploymentsListParamsWithHTTPClient(client *http.Client) *V1AboutDeploymentsListParams {
	return &V1AboutDeploymentsListParams{
		HTTPClient: client,
	}
}

/*
V1AboutDeploymentsListParams contains all the parameters to send to the API endpoint

	for the v1 about deployments list operation.

	Typically these are written to a http.Request.
*/
type V1AboutDeploymentsListParams struct {

	/* Contract.

	   Filter by Safe contract name
	*/
	Contract *string

	/* Version.

	   Filter by Safe version
	*/
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 about deployments list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutDeploymentsListParams) WithDefaults() *V1AboutDeploymentsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 about deployments list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AboutDeploymentsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) WithTimeout(timeout time.Duration) *V1AboutDeploymentsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) WithContext(ctx context.Context) *V1AboutDeploymentsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) WithHTTPClient(client *http.Client) *V1AboutDeploymentsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContract adds the contract to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) WithContract(contract *string) *V1AboutDeploymentsListParams {
	o.SetContract(contract)
	return o
}

// SetContract adds the contract to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) SetContract(contract *string) {
	o.Contract = contract
}

// WithVersion adds the version to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) WithVersion(version *string) *V1AboutDeploymentsListParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the v1 about deployments list params
func (o *V1AboutDeploymentsListParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *V1AboutDeploymentsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Contract != nil {

		// query param contract
		var qrContract string

		if o.Contract != nil {
			qrContract = *o.Contract
		}
		qContract := qrContract
		if qContract != "" {

			if err := r.SetQueryParam("contract", qContract); err != nil {
				return err
			}
		}
	}

	if o.Version != nil {

		// query param version
		var qrVersion string

		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {

			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
