// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// NewV1MessagesSignaturesCreateParams creates a new V1MessagesSignaturesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1MessagesSignaturesCreateParams() *V1MessagesSignaturesCreateParams {
	return &V1MessagesSignaturesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1MessagesSignaturesCreateParamsWithTimeout creates a new V1MessagesSignaturesCreateParams object
// with the ability to set a timeout on a request.
func NewV1MessagesSignaturesCreateParamsWithTimeout(timeout time.Duration) *V1MessagesSignaturesCreateParams {
	return &V1MessagesSignaturesCreateParams{
		timeout: timeout,
	}
}

// NewV1MessagesSignaturesCreateParamsWithContext creates a new V1MessagesSignaturesCreateParams object
// with the ability to set a context for a request.
func NewV1MessagesSignaturesCreateParamsWithContext(ctx context.Context) *V1MessagesSignaturesCreateParams {
	return &V1MessagesSignaturesCreateParams{
		Context: ctx,
	}
}

// NewV1MessagesSignaturesCreateParamsWithHTTPClient creates a new V1MessagesSignaturesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1MessagesSignaturesCreateParamsWithHTTPClient(client *http.Client) *V1MessagesSignaturesCreateParams {
	return &V1MessagesSignaturesCreateParams{
		HTTPClient: client,
	}
}

/*
V1MessagesSignaturesCreateParams contains all the parameters to send to the API endpoint

	for the v1 messages signatures create operation.

	Typically these are written to a http.Request.
*/
type V1MessagesSignaturesCreateParams struct {

	// Data.
	Data *models.SafeMessageSignature

	// MessageHash.
	MessageHash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 messages signatures create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1MessagesSignaturesCreateParams) WithDefaults() *V1MessagesSignaturesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 messages signatures create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1MessagesSignaturesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) WithTimeout(timeout time.Duration) *V1MessagesSignaturesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) WithContext(ctx context.Context) *V1MessagesSignaturesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) WithHTTPClient(client *http.Client) *V1MessagesSignaturesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) WithData(data *models.SafeMessageSignature) *V1MessagesSignaturesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) SetData(data *models.SafeMessageSignature) {
	o.Data = data
}

// WithMessageHash adds the messageHash to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) WithMessageHash(messageHash string) *V1MessagesSignaturesCreateParams {
	o.SetMessageHash(messageHash)
	return o
}

// SetMessageHash adds the messageHash to the v1 messages signatures create params
func (o *V1MessagesSignaturesCreateParams) SetMessageHash(messageHash string) {
	o.MessageHash = messageHash
}

// WriteToRequest writes these params to a swagger request
func (o *V1MessagesSignaturesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param message_hash
	if err := r.SetPathParam("message_hash", o.MessageHash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
