// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1MessagesSignaturesCreateReader is a Reader for the V1MessagesSignaturesCreate structure.
type V1MessagesSignaturesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1MessagesSignaturesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewV1MessagesSignaturesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/messages/{message_hash}/signatures/] v1_messages_signatures_create", response, response.Code())
	}
}

// NewV1MessagesSignaturesCreateCreated creates a V1MessagesSignaturesCreateCreated with default headers values
func NewV1MessagesSignaturesCreateCreated() *V1MessagesSignaturesCreateCreated {
	return &V1MessagesSignaturesCreateCreated{}
}

/*
V1MessagesSignaturesCreateCreated describes a response with status code 201, with default header values.

Created
*/
type V1MessagesSignaturesCreateCreated struct {
}

// IsSuccess returns true when this v1 messages signatures create created response has a 2xx status code
func (o *V1MessagesSignaturesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 messages signatures create created response has a 3xx status code
func (o *V1MessagesSignaturesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 messages signatures create created response has a 4xx status code
func (o *V1MessagesSignaturesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 messages signatures create created response has a 5xx status code
func (o *V1MessagesSignaturesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 messages signatures create created response a status code equal to that given
func (o *V1MessagesSignaturesCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the v1 messages signatures create created response
func (o *V1MessagesSignaturesCreateCreated) Code() int {
	return 201
}

func (o *V1MessagesSignaturesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /v1/messages/{message_hash}/signatures/][%d] v1MessagesSignaturesCreateCreated", 201)
}

func (o *V1MessagesSignaturesCreateCreated) String() string {
	return fmt.Sprintf("[POST /v1/messages/{message_hash}/signatures/][%d] v1MessagesSignaturesCreateCreated", 201)
}

func (o *V1MessagesSignaturesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
