// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// NewV1SafesMessagesCreateParams creates a new V1SafesMessagesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1SafesMessagesCreateParams() *V1SafesMessagesCreateParams {
	return &V1SafesMessagesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1SafesMessagesCreateParamsWithTimeout creates a new V1SafesMessagesCreateParams object
// with the ability to set a timeout on a request.
func NewV1SafesMessagesCreateParamsWithTimeout(timeout time.Duration) *V1SafesMessagesCreateParams {
	return &V1SafesMessagesCreateParams{
		timeout: timeout,
	}
}

// NewV1SafesMessagesCreateParamsWithContext creates a new V1SafesMessagesCreateParams object
// with the ability to set a context for a request.
func NewV1SafesMessagesCreateParamsWithContext(ctx context.Context) *V1SafesMessagesCreateParams {
	return &V1SafesMessagesCreateParams{
		Context: ctx,
	}
}

// NewV1SafesMessagesCreateParamsWithHTTPClient creates a new V1SafesMessagesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1SafesMessagesCreateParamsWithHTTPClient(client *http.Client) *V1SafesMessagesCreateParams {
	return &V1SafesMessagesCreateParams{
		HTTPClient: client,
	}
}

/*
V1SafesMessagesCreateParams contains all the parameters to send to the API endpoint

	for the v1 safes messages create operation.

	Typically these are written to a http.Request.
*/
type V1SafesMessagesCreateParams struct {

	// Address.
	Address string

	// Data.
	Data *models.SafeMessage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 safes messages create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1SafesMessagesCreateParams) WithDefaults() *V1SafesMessagesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 safes messages create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1SafesMessagesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) WithTimeout(timeout time.Duration) *V1SafesMessagesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) WithContext(ctx context.Context) *V1SafesMessagesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) WithHTTPClient(client *http.Client) *V1SafesMessagesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) WithAddress(address string) *V1SafesMessagesCreateParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) SetAddress(address string) {
	o.Address = address
}

// WithData adds the data to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) WithData(data *models.SafeMessage) *V1SafesMessagesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the v1 safes messages create params
func (o *V1SafesMessagesCreateParams) SetData(data *models.SafeMessage) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *V1SafesMessagesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
