// Code generated by go-swagger; DO NOT EDIT.

package data_decoder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1DataDecoderCreateReader is a Reader for the V1DataDecoderCreate structure.
type V1DataDecoderCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1DataDecoderCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1DataDecoderCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewV1DataDecoderCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1DataDecoderCreateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/data-decoder/] v1_data-decoder_create", response, response.Code())
	}
}

// NewV1DataDecoderCreateOK creates a V1DataDecoderCreateOK with default headers values
func NewV1DataDecoderCreateOK() *V1DataDecoderCreateOK {
	return &V1DataDecoderCreateOK{}
}

/*
V1DataDecoderCreateOK describes a response with status code 200, with default header values.

Decoded data
*/
type V1DataDecoderCreateOK struct {
}

// IsSuccess returns true when this v1 data decoder create o k response has a 2xx status code
func (o *V1DataDecoderCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 data decoder create o k response has a 3xx status code
func (o *V1DataDecoderCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 data decoder create o k response has a 4xx status code
func (o *V1DataDecoderCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 data decoder create o k response has a 5xx status code
func (o *V1DataDecoderCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 data decoder create o k response a status code equal to that given
func (o *V1DataDecoderCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 data decoder create o k response
func (o *V1DataDecoderCreateOK) Code() int {
	return 200
}

func (o *V1DataDecoderCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1/data-decoder/][%d] v1DataDecoderCreateOK", 200)
}

func (o *V1DataDecoderCreateOK) String() string {
	return fmt.Sprintf("[POST /v1/data-decoder/][%d] v1DataDecoderCreateOK", 200)
}

func (o *V1DataDecoderCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV1DataDecoderCreateNotFound creates a V1DataDecoderCreateNotFound with default headers values
func NewV1DataDecoderCreateNotFound() *V1DataDecoderCreateNotFound {
	return &V1DataDecoderCreateNotFound{}
}

/*
V1DataDecoderCreateNotFound describes a response with status code 404, with default header values.

Cannot find function selector to decode data
*/
type V1DataDecoderCreateNotFound struct {
}

// IsSuccess returns true when this v1 data decoder create not found response has a 2xx status code
func (o *V1DataDecoderCreateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 data decoder create not found response has a 3xx status code
func (o *V1DataDecoderCreateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 data decoder create not found response has a 4xx status code
func (o *V1DataDecoderCreateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 data decoder create not found response has a 5xx status code
func (o *V1DataDecoderCreateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 data decoder create not found response a status code equal to that given
func (o *V1DataDecoderCreateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1 data decoder create not found response
func (o *V1DataDecoderCreateNotFound) Code() int {
	return 404
}

func (o *V1DataDecoderCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/data-decoder/][%d] v1DataDecoderCreateNotFound", 404)
}

func (o *V1DataDecoderCreateNotFound) String() string {
	return fmt.Sprintf("[POST /v1/data-decoder/][%d] v1DataDecoderCreateNotFound", 404)
}

func (o *V1DataDecoderCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV1DataDecoderCreateUnprocessableEntity creates a V1DataDecoderCreateUnprocessableEntity with default headers values
func NewV1DataDecoderCreateUnprocessableEntity() *V1DataDecoderCreateUnprocessableEntity {
	return &V1DataDecoderCreateUnprocessableEntity{}
}

/*
V1DataDecoderCreateUnprocessableEntity describes a response with status code 422, with default header values.

Invalid data
*/
type V1DataDecoderCreateUnprocessableEntity struct {
}

// IsSuccess returns true when this v1 data decoder create unprocessable entity response has a 2xx status code
func (o *V1DataDecoderCreateUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 data decoder create unprocessable entity response has a 3xx status code
func (o *V1DataDecoderCreateUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 data decoder create unprocessable entity response has a 4xx status code
func (o *V1DataDecoderCreateUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 data decoder create unprocessable entity response has a 5xx status code
func (o *V1DataDecoderCreateUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 data decoder create unprocessable entity response a status code equal to that given
func (o *V1DataDecoderCreateUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v1 data decoder create unprocessable entity response
func (o *V1DataDecoderCreateUnprocessableEntity) Code() int {
	return 422
}

func (o *V1DataDecoderCreateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/data-decoder/][%d] v1DataDecoderCreateUnprocessableEntity", 422)
}

func (o *V1DataDecoderCreateUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /v1/data-decoder/][%d] v1DataDecoderCreateUnprocessableEntity", 422)
}

func (o *V1DataDecoderCreateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
