// Code generated by go-swagger; DO NOT EDIT.

package delegates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// NewV1DelegatesCreateParams creates a new V1DelegatesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1DelegatesCreateParams() *V1DelegatesCreateParams {
	return &V1DelegatesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1DelegatesCreateParamsWithTimeout creates a new V1DelegatesCreateParams object
// with the ability to set a timeout on a request.
func NewV1DelegatesCreateParamsWithTimeout(timeout time.Duration) *V1DelegatesCreateParams {
	return &V1DelegatesCreateParams{
		timeout: timeout,
	}
}

// NewV1DelegatesCreateParamsWithContext creates a new V1DelegatesCreateParams object
// with the ability to set a context for a request.
func NewV1DelegatesCreateParamsWithContext(ctx context.Context) *V1DelegatesCreateParams {
	return &V1DelegatesCreateParams{
		Context: ctx,
	}
}

// NewV1DelegatesCreateParamsWithHTTPClient creates a new V1DelegatesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1DelegatesCreateParamsWithHTTPClient(client *http.Client) *V1DelegatesCreateParams {
	return &V1DelegatesCreateParams{
		HTTPClient: client,
	}
}

/*
V1DelegatesCreateParams contains all the parameters to send to the API endpoint

	for the v1 delegates create operation.

	Typically these are written to a http.Request.
*/
type V1DelegatesCreateParams struct {

	// Data.
	Data *models.Delegate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 delegates create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1DelegatesCreateParams) WithDefaults() *V1DelegatesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 delegates create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1DelegatesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 delegates create params
func (o *V1DelegatesCreateParams) WithTimeout(timeout time.Duration) *V1DelegatesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 delegates create params
func (o *V1DelegatesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 delegates create params
func (o *V1DelegatesCreateParams) WithContext(ctx context.Context) *V1DelegatesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 delegates create params
func (o *V1DelegatesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 delegates create params
func (o *V1DelegatesCreateParams) WithHTTPClient(client *http.Client) *V1DelegatesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 delegates create params
func (o *V1DelegatesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the v1 delegates create params
func (o *V1DelegatesCreateParams) WithData(data *models.Delegate) *V1DelegatesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the v1 delegates create params
func (o *V1DelegatesCreateParams) SetData(data *models.Delegate) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *V1DelegatesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
