// Code generated by go-swagger; DO NOT EDIT.

package delegates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "omni-balance/utils/safe_api"
)

// NewV1DelegatesDeleteParams creates a new V1DelegatesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1DelegatesDeleteParams() *V1DelegatesDeleteParams {
	return &V1DelegatesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1DelegatesDeleteParamsWithTimeout creates a new V1DelegatesDeleteParams object
// with the ability to set a timeout on a request.
func NewV1DelegatesDeleteParamsWithTimeout(timeout time.Duration) *V1DelegatesDeleteParams {
	return &V1DelegatesDeleteParams{
		timeout: timeout,
	}
}

// NewV1DelegatesDeleteParamsWithContext creates a new V1DelegatesDeleteParams object
// with the ability to set a context for a request.
func NewV1DelegatesDeleteParamsWithContext(ctx context.Context) *V1DelegatesDeleteParams {
	return &V1DelegatesDeleteParams{
		Context: ctx,
	}
}

// NewV1DelegatesDeleteParamsWithHTTPClient creates a new V1DelegatesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1DelegatesDeleteParamsWithHTTPClient(client *http.Client) *V1DelegatesDeleteParams {
	return &V1DelegatesDeleteParams{
		HTTPClient: client,
	}
}

/*
V1DelegatesDeleteParams contains all the parameters to send to the API endpoint

	for the v1 delegates delete operation.

	Typically these are written to a http.Request.
*/
type V1DelegatesDeleteParams struct {

	// Data.
	Data *models.DelegateDelete

	// DelegateAddress.
	DelegateAddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 delegates delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1DelegatesDeleteParams) WithDefaults() *V1DelegatesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 delegates delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1DelegatesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) WithTimeout(timeout time.Duration) *V1DelegatesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) WithContext(ctx context.Context) *V1DelegatesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) WithHTTPClient(client *http.Client) *V1DelegatesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) WithData(data *models.DelegateDelete) *V1DelegatesDeleteParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) SetData(data *models.DelegateDelete) {
	o.Data = data
}

// WithDelegateAddress adds the delegateAddress to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) WithDelegateAddress(delegateAddress string) *V1DelegatesDeleteParams {
	o.SetDelegateAddress(delegateAddress)
	return o
}

// SetDelegateAddress adds the delegateAddress to the v1 delegates delete params
func (o *V1DelegatesDeleteParams) SetDelegateAddress(delegateAddress string) {
	o.DelegateAddress = delegateAddress
}

// WriteToRequest writes these params to a swagger request
func (o *V1DelegatesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param delegate_address
	if err := r.SetPathParam("delegate_address", o.DelegateAddress); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
