// Code generated by go-swagger; DO NOT EDIT.

package delegates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewV2DelegatesListParams creates a new V2DelegatesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV2DelegatesListParams() *V2DelegatesListParams {
	return &V2DelegatesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV2DelegatesListParamsWithTimeout creates a new V2DelegatesListParams object
// with the ability to set a timeout on a request.
func NewV2DelegatesListParamsWithTimeout(timeout time.Duration) *V2DelegatesListParams {
	return &V2DelegatesListParams{
		timeout: timeout,
	}
}

// NewV2DelegatesListParamsWithContext creates a new V2DelegatesListParams object
// with the ability to set a context for a request.
func NewV2DelegatesListParamsWithContext(ctx context.Context) *V2DelegatesListParams {
	return &V2DelegatesListParams{
		Context: ctx,
	}
}

// NewV2DelegatesListParamsWithHTTPClient creates a new V2DelegatesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewV2DelegatesListParamsWithHTTPClient(client *http.Client) *V2DelegatesListParams {
	return &V2DelegatesListParams{
		HTTPClient: client,
	}
}

/*
V2DelegatesListParams contains all the parameters to send to the API endpoint

	for the v2 delegates list operation.

	Typically these are written to a http.Request.
*/
type V2DelegatesListParams struct {

	/* Delegate.

	   delegate
	*/
	Delegate *string

	/* Delegator.

	   delegator
	*/
	Delegator *string

	/* Label.

	   label
	*/
	Label *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	/* Safe.

	   safe
	*/
	Safe *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v2 delegates list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2DelegatesListParams) WithDefaults() *V2DelegatesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v2 delegates list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2DelegatesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v2 delegates list params
func (o *V2DelegatesListParams) WithTimeout(timeout time.Duration) *V2DelegatesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 delegates list params
func (o *V2DelegatesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 delegates list params
func (o *V2DelegatesListParams) WithContext(ctx context.Context) *V2DelegatesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 delegates list params
func (o *V2DelegatesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 delegates list params
func (o *V2DelegatesListParams) WithHTTPClient(client *http.Client) *V2DelegatesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 delegates list params
func (o *V2DelegatesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegate adds the delegate to the v2 delegates list params
func (o *V2DelegatesListParams) WithDelegate(delegate *string) *V2DelegatesListParams {
	o.SetDelegate(delegate)
	return o
}

// SetDelegate adds the delegate to the v2 delegates list params
func (o *V2DelegatesListParams) SetDelegate(delegate *string) {
	o.Delegate = delegate
}

// WithDelegator adds the delegator to the v2 delegates list params
func (o *V2DelegatesListParams) WithDelegator(delegator *string) *V2DelegatesListParams {
	o.SetDelegator(delegator)
	return o
}

// SetDelegator adds the delegator to the v2 delegates list params
func (o *V2DelegatesListParams) SetDelegator(delegator *string) {
	o.Delegator = delegator
}

// WithLabel adds the label to the v2 delegates list params
func (o *V2DelegatesListParams) WithLabel(label *string) *V2DelegatesListParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the v2 delegates list params
func (o *V2DelegatesListParams) SetLabel(label *string) {
	o.Label = label
}

// WithLimit adds the limit to the v2 delegates list params
func (o *V2DelegatesListParams) WithLimit(limit *int64) *V2DelegatesListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the v2 delegates list params
func (o *V2DelegatesListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the v2 delegates list params
func (o *V2DelegatesListParams) WithOffset(offset *int64) *V2DelegatesListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the v2 delegates list params
func (o *V2DelegatesListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSafe adds the safe to the v2 delegates list params
func (o *V2DelegatesListParams) WithSafe(safe *string) *V2DelegatesListParams {
	o.SetSafe(safe)
	return o
}

// SetSafe adds the safe to the v2 delegates list params
func (o *V2DelegatesListParams) SetSafe(safe *string) {
	o.Safe = safe
}

// WriteToRequest writes these params to a swagger request
func (o *V2DelegatesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Delegate != nil {

		// query param delegate
		var qrDelegate string

		if o.Delegate != nil {
			qrDelegate = *o.Delegate
		}
		qDelegate := qrDelegate
		if qDelegate != "" {

			if err := r.SetQueryParam("delegate", qDelegate); err != nil {
				return err
			}
		}
	}

	if o.Delegator != nil {

		// query param delegator
		var qrDelegator string

		if o.Delegator != nil {
			qrDelegator = *o.Delegator
		}
		qDelegator := qrDelegator
		if qDelegator != "" {

			if err := r.SetQueryParam("delegator", qDelegator); err != nil {
				return err
			}
		}
	}

	if o.Label != nil {

		// query param label
		var qrLabel string

		if o.Label != nil {
			qrLabel = *o.Label
		}
		qLabel := qrLabel
		if qLabel != "" {

			if err := r.SetQueryParam("label", qLabel); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Safe != nil {

		// query param safe
		var qrSafe string

		if o.Safe != nil {
			qrSafe = *o.Safe
		}
		qSafe := qrSafe
		if qSafe != "" {

			if err := r.SetQueryParam("safe", qSafe); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
