// Code generated by go-swagger; DO NOT EDIT.

package delegates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V2DelegatesDeleteReader is a Reader for the V2DelegatesDelete structure.
type V2DelegatesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2DelegatesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV2DelegatesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV2DelegatesDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV2DelegatesDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV2DelegatesDeleteUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /v2/delegates/{delegate_address}/] v2_delegates_delete", response, response.Code())
	}
}

// NewV2DelegatesDeleteNoContent creates a V2DelegatesDeleteNoContent with default headers values
func NewV2DelegatesDeleteNoContent() *V2DelegatesDeleteNoContent {
	return &V2DelegatesDeleteNoContent{}
}

/*
V2DelegatesDeleteNoContent describes a response with status code 204, with default header values.

Deleted
*/
type V2DelegatesDeleteNoContent struct {
}

// IsSuccess returns true when this v2 delegates delete no content response has a 2xx status code
func (o *V2DelegatesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v2 delegates delete no content response has a 3xx status code
func (o *V2DelegatesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delegates delete no content response has a 4xx status code
func (o *V2DelegatesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this v2 delegates delete no content response has a 5xx status code
func (o *V2DelegatesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 delegates delete no content response a status code equal to that given
func (o *V2DelegatesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the v2 delegates delete no content response
func (o *V2DelegatesDeleteNoContent) Code() int {
	return 204
}

func (o *V2DelegatesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteNoContent", 204)
}

func (o *V2DelegatesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteNoContent", 204)
}

func (o *V2DelegatesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV2DelegatesDeleteBadRequest creates a V2DelegatesDeleteBadRequest with default headers values
func NewV2DelegatesDeleteBadRequest() *V2DelegatesDeleteBadRequest {
	return &V2DelegatesDeleteBadRequest{}
}

/*
V2DelegatesDeleteBadRequest describes a response with status code 400, with default header values.

Malformed data
*/
type V2DelegatesDeleteBadRequest struct {
}

// IsSuccess returns true when this v2 delegates delete bad request response has a 2xx status code
func (o *V2DelegatesDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 delegates delete bad request response has a 3xx status code
func (o *V2DelegatesDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delegates delete bad request response has a 4xx status code
func (o *V2DelegatesDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 delegates delete bad request response has a 5xx status code
func (o *V2DelegatesDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 delegates delete bad request response a status code equal to that given
func (o *V2DelegatesDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the v2 delegates delete bad request response
func (o *V2DelegatesDeleteBadRequest) Code() int {
	return 400
}

func (o *V2DelegatesDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteBadRequest", 400)
}

func (o *V2DelegatesDeleteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteBadRequest", 400)
}

func (o *V2DelegatesDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV2DelegatesDeleteNotFound creates a V2DelegatesDeleteNotFound with default headers values
func NewV2DelegatesDeleteNotFound() *V2DelegatesDeleteNotFound {
	return &V2DelegatesDeleteNotFound{}
}

/*
V2DelegatesDeleteNotFound describes a response with status code 404, with default header values.

Delegate not found
*/
type V2DelegatesDeleteNotFound struct {
}

// IsSuccess returns true when this v2 delegates delete not found response has a 2xx status code
func (o *V2DelegatesDeleteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 delegates delete not found response has a 3xx status code
func (o *V2DelegatesDeleteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delegates delete not found response has a 4xx status code
func (o *V2DelegatesDeleteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 delegates delete not found response has a 5xx status code
func (o *V2DelegatesDeleteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 delegates delete not found response a status code equal to that given
func (o *V2DelegatesDeleteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v2 delegates delete not found response
func (o *V2DelegatesDeleteNotFound) Code() int {
	return 404
}

func (o *V2DelegatesDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteNotFound", 404)
}

func (o *V2DelegatesDeleteNotFound) String() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteNotFound", 404)
}

func (o *V2DelegatesDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV2DelegatesDeleteUnprocessableEntity creates a V2DelegatesDeleteUnprocessableEntity with default headers values
func NewV2DelegatesDeleteUnprocessableEntity() *V2DelegatesDeleteUnprocessableEntity {
	return &V2DelegatesDeleteUnprocessableEntity{}
}

/*
V2DelegatesDeleteUnprocessableEntity describes a response with status code 422, with default header values.

Invalid Ethereum address/Error processing data
*/
type V2DelegatesDeleteUnprocessableEntity struct {
}

// IsSuccess returns true when this v2 delegates delete unprocessable entity response has a 2xx status code
func (o *V2DelegatesDeleteUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 delegates delete unprocessable entity response has a 3xx status code
func (o *V2DelegatesDeleteUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delegates delete unprocessable entity response has a 4xx status code
func (o *V2DelegatesDeleteUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 delegates delete unprocessable entity response has a 5xx status code
func (o *V2DelegatesDeleteUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 delegates delete unprocessable entity response a status code equal to that given
func (o *V2DelegatesDeleteUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v2 delegates delete unprocessable entity response
func (o *V2DelegatesDeleteUnprocessableEntity) Code() int {
	return 422
}

func (o *V2DelegatesDeleteUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteUnprocessableEntity", 422)
}

func (o *V2DelegatesDeleteUnprocessableEntity) String() string {
	return fmt.Sprintf("[DELETE /v2/delegates/{delegate_address}/][%d] v2DelegatesDeleteUnprocessableEntity", 422)
}

func (o *V2DelegatesDeleteUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
